### ISSUE TITLE
how to run application

### ISSUE THREAD

**Issue by newzen** [francisco-betancourt/ctrlpyme4#28]
Hello,

I'm new to web2py, would you provide instructions for run yours application?

Import your application from web2py using git

https://github.com/francisco-betancourt/web2py.git

Traceback (most recent call last):
  File "/Disk2/Disk2p1/pos-from-git/web2/web2py/gluon/main.py", line 449, in wsgibase
    serve_controller(request, response, session)
  File "/Disk2/Disk2p1/pos-from-git/web2/web2py/gluon/main.py", line 185, in serve_controller
    run_models_in(environment)
  File "/Disk2/Disk2p1/pos-from-git/web2/web2py/gluon/compileapp.py", line 576, in run_models_in
    restricted(code, environment, layer=model)
  File "/Disk2/Disk2p1/pos-from-git/web2/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/Disk2/Disk2p1/pos-from-git/web2/web2py/applications/ctrlpyme4/models/db.py", line 18, in <module>
    from constants import CONF, BAG_ACTIVE
  File "/Disk2/Disk2p1/pos-from-git/web2/web2py/gluon/custom_import.py", line 95, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
  File "applications/ctrlpyme4/modules/constants.py", line 25, in <module>
    CONF = AppConfig(reload=True)
  File "/Disk2/Disk2p1/pos-from-git/web2/web2py/gluon/contrib/appconfig.py", line 45, in AppConfig
    setattr(AppConfig, instance_name, AppConfigLoader(_args, *_vars))
  File "/Disk2/Disk2p1/pos-from-git/web2/web2py/gluon/contrib/appconfig.py", line 117, in **init**
    raise BaseException("Config file not found")
BaseException: Config file not found

<type 'exceptions.BaseException'>(Config file not found)

Thanks in advance

**Comment by djrm** [comment]
yes you need the appconfig.ini inside the private folder, it is not on github because it is supposed to be private, but here is a template for the appconfig.ini

[appconfig.ini.zip](https://github.com/francisco-betancourt/ctrlpyme4/files/402008/appconfig.ini.zip)

**Comment by newzen** [comment]
Hey, thanks . It's work now.

Have you any database dump with existent user and products ?

Could it be added to the repo?

Thanks

**Comment by djrm** [comment]
No, currently there is not test db, maybe it could be added in the future as a separate download for developers.
